# Generated by Django 3.0 on 2024-06-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empployee',
            new_name='Employee',
        ),
    ]
