# Generated by Django 3.0 on 2024-07-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20240703_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_num',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
